// What the REST API returns for an article.
export interface ArticleView {
  articleId: string;

  title: string;

  url: string;

  source: string;

  summary?: string;

  // ISO datetime strings.
  publishedAt?: string;

  discoveredAt: string;

  category: string;

  status: ArticleData["status"];
}

export interface ArticleData {
  articleId: string;

  title: string;

  url: string;

  source: string;

  summary?: string;

  publishedAt?: Date;

  discoveredAt: Date;

  category: string;

  // Generated by the editorial pipeline.
  headline?: string;

  body?: string;

  imageUrl?: string;

  // Added after event clustering.
  eventId?: string;

  status:
    | "discovered"
    | "researching"
    | "writing"
    | "drafted"
    | "edited"
    | "fact-checked"
    | "ready"
    | "published";
}
