// What the REST API returns for an article.
import type {
  ArticleStatus,
} from "@newsgarden/shared";

export interface ArticleView {
  articleId: string;

  title: string;

  url: string;

  source: string;

  summary?: string;

  // Generated by the editorial pipeline; included so the
  // article page can render the full story.
  headline?: string;

  body?: string;

  imageUrl?: string;

  // Attribution for web-sourced images.
  imageCredit?: string;

  imageSourceUrl?: string;

  // ISO datetime strings.
  publishedAt?: string;

  discoveredAt: string;

  category: string;

  status: ArticleData["status"];
}

export interface ArticleData {
  articleId: string;

  title: string;

  url: string;

  source: string;

  summary?: string;

  publishedAt?: Date;

  discoveredAt: Date;

  category: string;

  // Generated by the editorial pipeline.
  headline?: string;

  body?: string;

  imageUrl?: string;

  // Attribution for web-sourced images.
  imageCredit?: string;

  imageSourceUrl?: string;

  // Added after event clustering.
  eventId?: string;

  status: ArticleStatus;
}
