// Realtime event names shared by the backend and the frontend.
// String values must stay exactly as-is: other areas depend on them.
export const EVENTS = {
  AGENT_STARTED: "AGENT_STARTED",
  AGENT_TASK_COMPLETED: "AGENT_TASK_COMPLETED",
  AGENT_TASK_FAILED: "AGENT_TASK_FAILED",
  AGENT_MOVEMENT_REQUESTED: "AGENT_MOVEMENT_REQUESTED",
  AGENT_IDLE: "AGENT_IDLE",
  TASK_CREATED: "TASK_CREATED",
  TASK_STARTED: "TASK_STARTED",
  ARTICLE_DISCOVERED: "ARTICLE_DISCOVERED",
  EDITION_STAGE_COMPLETED: "EDITION_STAGE_COMPLETED",
  EDITION_READY_FOR_APPROVAL: "EDITION_READY_FOR_APPROVAL",
  EDITION_APPROVED: "EDITION_APPROVED",
  EDITION_PUBLISHED: "EDITION_PUBLISHED",
  EDITION_REVISION_REQUESTED: "EDITION_REVISION_REQUESTED",
} as const;

export type EventName = (typeof EVENTS)[keyof typeof EVENTS];
