"""
Cuts feathered sprite patches out of the reference scene so GSAP can animate
them in place. Run:  python3 scripts/extract_sprites.py [--debug]
Writes PNGs to public/campus/{characters,decorations} and src/lib/sprites.ts
"""
import json, os, sys
from PIL import Image, ImageDraw, ImageFilter

SRC = os.environ.get("REF", "public/campus/backgrounds/campus-reference.png")
DEBUG = "--debug" in sys.argv

# id, group, kind, x, y, w, h, shape, feather
SPECS = [
  # ---- characters ----
  ("newsroom-cat",  "characters", "typist", 320, 184, 62, 66, "ellipse", 6),
  ("editorial-cat", "characters", "typist", 696, 208, 56, 58, "ellipse", 6),
  ("design-cat",    "characters", "typist", 1030, 196, 58, 66, "ellipse", 6),
  ("raccoon",       "characters", "typist", 284, 482, 58, 60, "ellipse", 6),
  ("visual-cat",    "characters", "typist", 272, 704, 62, 64, "ellipse", 6),
  ("cafe-calico",   "characters", "sip",    624, 526, 74, 66, "ellipse", 6),
  ("cafe-black",    "characters", "sip",    728, 510, 64, 68, "ellipse", 6),
  ("manga-bunny",   "characters", "reader", 1050, 496, 66, 68, "ellipse", 6),
  ("badminton-orange", "characters", "rally-left",  870, 720, 62, 68, "ellipse", 6),
  ("badminton-grey",   "characters", "rally-right", 1012, 712, 70, 70, "ellipse", 6),
  ("gold-cat",      "characters", "pet",    952, 158, 46, 44, "ellipse", 5),
  ("pig",           "characters", "pet",    1128, 808, 40, 42, "ellipse", 5),
  ("astronaut-l",   "characters", "float",  158, 440, 46, 62, "ellipse", 5),
  ("astronaut-r",   "characters", "float",  396, 436, 46, 62, "ellipse", 5),
  # ---- plants / trees ----
  ("plant-newsroom-l", "decorations", "sway", 143, 140, 46, 83, "ellipse", 6),
  ("plant-newsroom-r", "decorations", "sway", 415, 148, 48, 52, "ellipse", 6),
  ("plant-center-tall","decorations", "sway", 546, 122, 48, 80, "ellipse", 6),
  ("plant-editorial-a","decorations", "sway", 808, 68, 46, 56, "ellipse", 6),
  ("plant-editorial-b","decorations", "sway", 812, 222, 48, 64, "ellipse", 6),
  ("plant-design-tall","decorations", "sway", 1138, 52, 62, 82, "ellipse", 6),
  ("plant-cafe-l",     "decorations", "sway", 524, 322, 44, 62, "ellipse", 6),
  ("plant-manga-r",    "decorations", "sway", 1152, 556, 50, 66, "ellipse", 6),
  ("plant-library-a",  "decorations", "sway", 950, 536, 50, 60, "ellipse", 6),
  ("plant-visual-a",   "decorations", "sway", 700, 655, 50, 98, "ellipse", 6),
  ("tree-left",  "decorations", "tree", 416, 806, 84, 124, "ellipse", 8),
  ("tree-right", "decorations", "tree", 728, 802, 100, 128, "ellipse", 8),
  ("bush-left",  "decorations", "tree", 212, 862, 76, 62, "ellipse", 6),
  ("bush-right", "decorations", "tree", 1250, 850, 66, 76, "ellipse", 6),
  ("flowers",    "decorations", "tree", 1456, 866, 60, 58, "ellipse", 6),
]

im = Image.open(SRC).convert("RGB")

def feathered(w, h, shape, f):
    m = Image.new("L", (w, h), 0)
    d = ImageDraw.Draw(m)
    box = [f, f, w - f, h - f]
    (d.ellipse if shape == "ellipse" else d.rounded_rectangle)(box, fill=255)
    return m.filter(ImageFilter.GaussianBlur(f / 1.6))

if DEBUG:
    dbg = im.copy(); d = ImageDraw.Draw(dbg)
    for id_, g, k, x, y, w, h, s, f in SPECS:
        d.rectangle([x, y, x + w, y + h], outline=(255, 0, 255), width=2)
        d.text((x + 2, y + 2), id_.replace("plant-", "p-"), fill=(255, 255, 0))
    dbg.save("/home/claude/debug_boxes.png"); sys.exit()

def clean_shuttle():
    import cv2, numpy as np
    x, y, w, h = 980, 704, 28, 30
    a = np.array(im.crop((x, y, x + w, y + h)))
    mask = ((a.min(axis=2) > 190)).astype("uint8") * 255
    mask = cv2.dilate(mask, np.ones((3, 3), np.uint8), iterations=2)
    out = cv2.inpaint(a, mask, 3, cv2.INPAINT_TELEA)
    Image.fromarray(out).save("public/campus/decorations/shuttle-clean.png")
    return dict(id="shuttle-clean", group="decorations", kind="static", x=x, y=y, w=w, h=h)

for g in ("characters", "decorations"):
    os.makedirs(f"public/campus/{g}", exist_ok=True)
rows = []
for id_, g, k, x, y, w, h, s, f in SPECS:
    patch = im.crop((x, y, x + w, y + h)).convert("RGBA")
    patch.putalpha(feathered(w, h, s, f))
    patch.save(f"public/campus/{g}/{id_}.png")
    rows.append(dict(id=id_, group=g, kind=k, x=x, y=y, w=w, h=h))

rows.append(clean_shuttle())
with open("src/lib/sprites.ts", "w") as fh:
    fh.write("// Generated by scripts/extract_sprites.py - do not edit by hand.\n")
    fh.write("export type SpriteKind =\n  | \"typist\" | \"sip\" | \"reader\" | \"rally-left\" | \"rally-right\"\n  | \"pet\" | \"float\" | \"sway\" | \"tree\" | \"static\";\n\n")
    fh.write("export interface SpriteDef { id: string; group: \"characters\" | \"decorations\"; kind: SpriteKind; x: number; y: number; w: number; h: number }\n\n")
    fh.write("export const SPRITES: SpriteDef[] = " + json.dumps(rows, indent=2) + ";\n")
print("wrote", len(rows), "sprites")
