// Generated by scripts/extract_sprites.py - do not edit by hand.
export type SpriteKind =
  | "typist" | "sip" | "reader" | "rally-left" | "rally-right"
  | "pet" | "float" | "sway" | "tree" | "static";

export interface SpriteDef { id: string; group: "characters" | "decorations"; kind: SpriteKind; x: number; y: number; w: number; h: number }

export const SPRITES: SpriteDef[] = [
  {
    "id": "newsroom-cat",
    "group": "characters",
    "kind": "typist",
    "x": 320,
    "y": 184,
    "w": 62,
    "h": 66
  },
  {
    "id": "editorial-cat",
    "group": "characters",
    "kind": "typist",
    "x": 696,
    "y": 208,
    "w": 56,
    "h": 58
  },
  {
    "id": "design-cat",
    "group": "characters",
    "kind": "typist",
    "x": 1030,
    "y": 196,
    "w": 58,
    "h": 66
  },
  {
    "id": "raccoon",
    "group": "characters",
    "kind": "typist",
    "x": 284,
    "y": 482,
    "w": 58,
    "h": 60
  },
  {
    "id": "visual-cat",
    "group": "characters",
    "kind": "typist",
    "x": 272,
    "y": 704,
    "w": 62,
    "h": 64
  },
  {
    "id": "cafe-calico",
    "group": "characters",
    "kind": "sip",
    "x": 624,
    "y": 526,
    "w": 74,
    "h": 66
  },
  {
    "id": "cafe-black",
    "group": "characters",
    "kind": "sip",
    "x": 728,
    "y": 510,
    "w": 64,
    "h": 68
  },
  {
    "id": "manga-bunny",
    "group": "characters",
    "kind": "reader",
    "x": 1050,
    "y": 496,
    "w": 66,
    "h": 68
  },
  {
    "id": "badminton-orange",
    "group": "characters",
    "kind": "rally-left",
    "x": 870,
    "y": 720,
    "w": 62,
    "h": 68
  },
  {
    "id": "badminton-grey",
    "group": "characters",
    "kind": "rally-right",
    "x": 1012,
    "y": 712,
    "w": 70,
    "h": 70
  },
  {
    "id": "gold-cat",
    "group": "characters",
    "kind": "pet",
    "x": 952,
    "y": 158,
    "w": 46,
    "h": 44
  },
  {
    "id": "pig",
    "group": "characters",
    "kind": "pet",
    "x": 1128,
    "y": 808,
    "w": 40,
    "h": 42
  },
  {
    "id": "astronaut-l",
    "group": "characters",
    "kind": "float",
    "x": 158,
    "y": 440,
    "w": 46,
    "h": 62
  },
  {
    "id": "astronaut-r",
    "group": "characters",
    "kind": "float",
    "x": 396,
    "y": 436,
    "w": 46,
    "h": 62
  },
  {
    "id": "plant-newsroom-l",
    "group": "decorations",
    "kind": "sway",
    "x": 143,
    "y": 140,
    "w": 46,
    "h": 83
  },
  {
    "id": "plant-newsroom-r",
    "group": "decorations",
    "kind": "sway",
    "x": 415,
    "y": 148,
    "w": 48,
    "h": 52
  },
  {
    "id": "plant-center-tall",
    "group": "decorations",
    "kind": "sway",
    "x": 546,
    "y": 122,
    "w": 48,
    "h": 80
  },
  {
    "id": "plant-editorial-a",
    "group": "decorations",
    "kind": "sway",
    "x": 808,
    "y": 68,
    "w": 46,
    "h": 56
  },
  {
    "id": "plant-editorial-b",
    "group": "decorations",
    "kind": "sway",
    "x": 812,
    "y": 222,
    "w": 48,
    "h": 64
  },
  {
    "id": "plant-design-tall",
    "group": "decorations",
    "kind": "sway",
    "x": 1138,
    "y": 52,
    "w": 62,
    "h": 82
  },
  {
    "id": "plant-cafe-l",
    "group": "decorations",
    "kind": "sway",
    "x": 524,
    "y": 322,
    "w": 44,
    "h": 62
  },
  {
    "id": "plant-manga-r",
    "group": "decorations",
    "kind": "sway",
    "x": 1152,
    "y": 556,
    "w": 50,
    "h": 66
  },
  {
    "id": "plant-library-a",
    "group": "decorations",
    "kind": "sway",
    "x": 950,
    "y": 536,
    "w": 50,
    "h": 60
  },
  {
    "id": "plant-visual-a",
    "group": "decorations",
    "kind": "sway",
    "x": 700,
    "y": 655,
    "w": 50,
    "h": 98
  },
  {
    "id": "tree-left",
    "group": "decorations",
    "kind": "tree",
    "x": 416,
    "y": 806,
    "w": 84,
    "h": 124
  },
  {
    "id": "tree-right",
    "group": "decorations",
    "kind": "tree",
    "x": 728,
    "y": 802,
    "w": 100,
    "h": 128
  },
  {
    "id": "bush-left",
    "group": "decorations",
    "kind": "tree",
    "x": 212,
    "y": 862,
    "w": 76,
    "h": 62
  },
  {
    "id": "bush-right",
    "group": "decorations",
    "kind": "tree",
    "x": 1250,
    "y": 850,
    "w": 66,
    "h": 76
  },
  {
    "id": "flowers",
    "group": "decorations",
    "kind": "tree",
    "x": 1456,
    "y": 866,
    "w": 60,
    "h": 58
  },
  {
    "id": "shuttle-clean",
    "group": "decorations",
    "kind": "static",
    "x": 980,
    "y": 704,
    "w": 28,
    "h": 30
  }
];
